//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy_football_crawler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FantasyFootballEF : DbContext
    {
        public FantasyFootballEF()
            : base("name=FantasyFootballEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<player> player { get; set; }
        public virtual DbSet<player_in_teams_info> player_in_teams_info { get; set; }
        public virtual DbSet<team> team { get; set; }
    }
}
