//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy_football_crawler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_in_teams_info
    {
        public int id { get; set; }
        public long player_id { get; set; }
        public System.DateTime date { get; set; }
        public int count { get; set; }
    
        public virtual player player { get; set; }
    }
}
